final List<String> dist = [
  'Select Region',
  'Hyderabad',
  'Ranga Reddy',
  'Khammam',
  'Kamareddy',
  'Adilabad',
  'Bhadradri Kothagudem',
  'Bayyaram Telangana 507211',
  'Jagtila',
  'Jayashankar Bhupalapally',
  'Jogulamba Gadwal',
  'Nagarkurnool',
  'Nalgonda',
  'Nirmal',
  'Wanaparthy',
  'Warangal Rural',
  'Warangal Urban',
  'Medak',
  'Medchal Malkajgiri',
  'Jangaon',
  'Rajanna Sircilla',
  'Karimnagar',
  'Komaram Bheem Asifabad',
  'Nizamabad',
  'Narayanpet',
  'Sanga Reddy',
  'Siddipet',
  'Suryapet',
  'Mahabubabad',
  'Mahabubanagar',
  'Mancherial',
  'Mulugu',
  'Peddapalli',
  'Vikarabad',
  'Yadadri Bhongir'
];
